name: snake-commit

on:
  schedule: [{cron: "0 * * * *"}]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: CarlosViniMSouza
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          token: ${{ secrets.ANIMATION_TOKEN }}
